// <auto-generated />
using System;
using ExamenRemitee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamenRemitee.Migrations
{
    [DbContext(typeof(ExamenRemiteeContext))]
    [Migration("20211221032712_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamenRemitee.Models.Consultas", b =>
                {
                    b.Property<int>("NroOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonedaDestino")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("MonedaDestinoMonto")
                        .HasColumnType("float");

                    b.Property<string>("MonedaOrigen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("MonedaOrigenMonto")
                        .HasColumnType("float");

                    b.HasKey("NroOrden");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("ExamenRemitee.Models.Cotizaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.Property<int?>("registroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("registroId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("ExamenRemitee.Models.RegistroCurrencyLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Exito")
                        .HasColumnType("bit");

                    b.Property<string>("MonedaFuente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliticaPrivacidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("TerminosURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("ExamenRemitee.Models.Cotizaciones", b =>
                {
                    b.HasOne("ExamenRemitee.Models.RegistroCurrencyLayer", "registro")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("registroId");

                    b.Navigation("registro");
                });

            modelBuilder.Entity("ExamenRemitee.Models.RegistroCurrencyLayer", b =>
                {
                    b.Navigation("Cotizaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
